@HOST=http://localhost:3000

GET {{HOST}}/api/posts

###
GET {{HOST}}/api/posts/15

###
POST {{HOST}}/api/posts
Content-Type: application/json

{
    "title": "Un post de prueba2",
    "description": "Probando la inserción de post desde API por segunda vez",
    "category": "Tecnología",
    "authorsId": 1
}

###
GET {{HOST}}/api/authors

###
GET {{HOST}}/api/authors/3

###
POST {{HOST}}/api/authors
Content-Type: application/json

{
    "email": "mateo@email.com",
    "name": "Mateo Ibañez",
    "image": "avatar_mateo.png"
}


###
GET {{HOST}}/api/authors/3/posts